M48
; DRILL file {KiCad (7.0.0)} date Wed Mar  8 00:24:58 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-08T00:24:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X5.7476Y-4.5339
X5.9445Y-4.5339
T2
X6.1291Y-3.0793
X6.2472Y-3.0793
T0
M30
